---
- name: Update apt
  hosts: all
  become: yes

  tasks:
    - name: Disable root ssh login
      ansible.builtin.command:
        cmd: sed -i 's/^#PermitRootLogin prohibit-password.*/PermitRootLogin no/' /etc/ssh/sshd_config

    - name: Update repositories
      ansible.builtin.apt:
          cache_valid_time: 86400
          update_cache: yes

- name: Install anti malware
  hosts: all
  become: yes
  roles:
    - malware

- name: Configure 100% swap space
  hosts: all
  become: yes
  roles:
    - swap

- name: Install fail2ban
  hosts: all
  become: yes
  roles:
    - fail2ban

- name: Lower mem consumption
  hosts: all
  become: yes
  roles:
    - lowmem

- name: Weekly reboot
  hosts: all
  become: yes
  roles:
    - reboot
