---
- name: stop and disable oracle cloud agent
  when: ansible_facts["chassis_asset_tag"] == "OracleCloud.com"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: False
    state: stopped
  with_items:
    - snap.oracle-cloud-agent.oracle-cloud-agent-updater
    - snap.oracle-cloud-agent.oracle-cloud-agent

- name: stop and disable snapd
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: False
    state: stopped
  with_items:
    - snapd.seeded
    - snapd.socket
    - snapd
