---
- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file_path }}"
  register: swap_file_check

- name: Create swap file
  ansible.builtin.command: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ ansible_memory_mb['real']['total'] }}"
  when: not swap_file_check.stat.exists

- name: Format swap file
  ansible.builtin.command: "mkswap {{ swap_file_path }}"
  when: not swap_file_check.stat.exists

- name: Set permissions for swap file
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    mode: '0600'

- name: Set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present

- name: Add swap to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file_path }}"
    line: "{{ swap_file_path }} none swap sw 0 0"

- name: Turn on swap
  ansible.builtin.command: swapon -a
