---
- name: check if swap file exists
  stat:
    path: "{{ swap_file_path }}"
  register: swap_file_check

- name: create swap file
  command: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ ansible_memory_mb['real']['total'] }}"
  when: not swap_file_check.stat.exists

- name: format swap file
  command: "mkswap {{ swap_file_path }}"
  when: not swap_file_check.stat.exists

- name: set permissions for swap file
  file:
    path: "{{ swap_file_path }}"
    mode: '0600'

- name: set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present

- name: add swap to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file_path }}"
    line: "{{ swap_file_path }} none swap sw 0 0"

- name: turn on swap
  command: swapon -a
