---
- name: install mailutils for reports
  ansible.builtin.apt:
    name: mailutils
    state: present

- name: install anti rootkit
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - chkrootkit
    - rkhunter

- name: rkhunter - use remote mirrors
  ansible.builtin.command:
    cmd: sed -i 's/^MIRRORS_MODE=1/MIRRORS_MODE=0/' /etc/rkhunter.conf

- name: rkhunter - update to use mirrors
  ansible.builtin.command:
    cmd: sed -i 's/^UPDATE_MIRRORS=0/UPDATE_MIRRORS=1/' /etc/rkhunter.conf

- name: rkhunter - use default WEB_CMD
  ansible.builtin.command:
    cmd: sed -i 's/^WEB_CMD=.*/WEB_CMD=""/' /etc/rkhunter.conf

- name: add crontab for chkrootkit
  ansible.builtin.cron:
    name: chkrootkit
    special_time: daily
    job: "/usr/sbin/chkrootkit 2>&1 | mail -s 'chkcrootkit output' root"

- name: add crontab for rkhunter
  ansible.builtin.cron:
    name: rkhunter
    special_time: daily
    job: "/usr/bin/rkhunter --check --nocolors --skip-keypress 2>&1 | mail -s 'rkhunter output' root"
