---
- name: install mailutils for reports
  ansible.builtin.apt:
    name: mailutils
    state: present

- name: install anti rootkit
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - chkrootkit
    - rkhunter

- name: add crontab for chkrootkit
  ansible.builtin.cron:
    name: chkrootkit
    special_time: daily
    job: "chkrootkit 2>&1 | mail -s 'chkcrootkit output' root"

- name: add crontab for rkhunter
  ansible.builtin.cron:
    name: rkhunter
    special_time: daily
    job: "rkhunter --cronjob 2>&1 | mail -s 'rkhunter output' root"
