---
- name: install dependencies
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: enable & run fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: True
    state: started
