---
- name: Install dependencies
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Strict ssh jail
  ansible.builtin.copy:
    src: sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: "root"
    group: "root"
    mode: "0644"

- name: Enable & run fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: True
    state: started
