---
- name: Install dependencies
  apt:
      name: fail2ban
      state: present

- name: Copy jail.local
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
